export { default as AccountsWidget } from "./AccountsWidget";
export { default as ActivityWidget } from "./ActivityWidget";
export { default as QuorumWidget } from "./QuorumWidget";
export { default as TotalBalanceWidget } from "./TotalBalanceWidget";
export { default as RequestsWidget } from "./RequestsWidget";
export { default as LastTransactionsWidget } from "./LastTransactionsWidget";
export { default as AssetsDistributionWidget } from "./AssetsDistributionWidget";
export { default as TransactionsGraphWidget } from "./TransactionsGraph";
export { default as UtxoGraphWidget } from "./UtxoGraph";
export { default as AccountQuickInfoWidget } from "./AccountQuickInfoWidget";
export { default as AccountLastTransactionsWidget } from "./AccountLastTransactionsWidget";
export { default as UtxoDistributionWidget } from "./UtxoDistributionWidget";
export { default as SubAccountsWidget } from "./SubAccountsWidget";
export { default as Widget, connectWidget } from "./Widget";
