// @flow

export const UTXO_PICKING_STRATEGY = {
  MERGE_OUTPUTS: "MERGE_OUTPUTS",
  DEEP_OUTPUTS_FIRST: "DEEP_OUTPUTS_FIRST",
  OPTIMIZE_SIZE: "OPTIMIZE_SIZE",
};

export type UtxoPickingStrategy = $Keys<typeof UTXO_PICKING_STRATEGY>;
